project:
  type: website
  output-dir: docs

website:
  title: "Isabelle T. Smith"
  favicon: chart-line.png
  page-footer: "2025"
  navbar:
    title: true
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/isabelletsmith
      - icon: github
        href: https://github.com/isabelle-smith/isabelle-smith.github.io

format:
  html:
    theme: none
    css: styles.css
    toc: true



